### ISSUE TITLE
DataSource is not proxied correctly with embedded postgres

### ISSUE THREAD

**Issue by pfilaretov** [adgadev/jplusone#9]
Hi,
I found JPlusOne a great tool to assert DB queries in integration tests with Spring Boot + Spring Data JPA.
It works fine with existing database, e.g. Postgres started in docker on my local machine.
However, I want integration tests to be self-contained, so I'm using embedded postgres, here are gradle dependencies:
```
testImplementation "io.zonky.test:embedded-postgres:1.3.1"
testImplementation "io.zonky.test:embedded-database-spring-test:2.1.1"
```

And when I run my `@SpringBootTest` class, `ReportGenerator` prints
```
No operations / statements matching report criteria found
```
...and I also have NPE thrown:
```
java.lang.NullPointerException
	at com.adgadev.jplusone.asserts.impl.rule.ExecutionFilter.matchesFrameStack(ExecutionFilter.java:65)
	at com.adgadev.jplusone.asserts.impl.rule.ExecutionFilter.getMatchingOperations(ExecutionFilter.java:51)
	at com.adgadev.jplusone.asserts.impl.rule.Rule.check(Rule.java:47)
	at com.adgadev.jplusone.asserts.impl.Assertion.check(Assertion.java:38)
	at com.adgadev.jplusone.asserts.impl.ConditionDoneBuilderImpl.check(ConditionDoneBuilderImpl.java:38)
	at com.example.MyIntegrationTest.save(MyIntegrationTest.java:92)
```
The reason is that embedded postgres replaces datasource bean with its own implementation, here is the log message it prints:
```
INFO 7976 --- [           main] EmbeddedDatabaseContextCustomizerFactory : Replacing 'dataSource' DataSource bean with embedded version
```
On the other hand, `ProxiedRootsBeanPostProcessor` is created with `useHikariDataSourceAspect` property set to `true`, which is calculated now in `JPlusOneAutoConfiguration.proxiedRootsBeanPostProcessor()` as follows:
```
boolean useHikariDataSourceAspect = applicationContext.containsBean("org.springframework.cloud.autoconfigure.RefreshAutoConfiguration");
```
So, in `ProxiedRootsBeanPostProcessor.postProcessAfterInitialization()` we have the following logic for datasource:
```
        if (bean instanceof DataSource) {
            if (useHikariDataSourceAspect) {
                log.debug("Using HikariDataSource aspect to intercept datasource connection creation");
            } else {
                log.debug("DataSource wrapped in the proxy");
                return new DataSourceProxy((DataSource) bean, stateListener);
            }
        }
```
And since `useHikariDataSourceAspect` is `true`, it will not wrap the datasource in the proxy now.

I tried to run the test in IDE in debug mode and manually set `useHikariDataSourceAspect` to `false`, and then the test worked fine, i.e. no NPE and `ReportGenerator` printed queries.

So, is it possible to fix this? The very first idea that comes to my mind is to have another configuration property in `JPlusOneProperties`, something like `force-datasource-proxy`, which will be set to `false` by default and will be used along with existing logic to decide which value to set for `useHikariDataSourceAspect`.
And then, with the real database I can leave this property set to default value, and with embedded postgres I can set it to `true` to make sure datasource is wrapped in proxy correctly.

P.S.
I'm using spring boot 2.5.7.

**Comment by pfilaretov** [comment]
Another option could be to create an aspect for `DataSource.getConnection()`, similar to `HikariDataSourceAspect`

**Comment by adgadev** [comment]
Thank you for so detailed issue description and analysis. I really appreciate your effort. It definitely can be fixed. 

The criteria for choosing aspect flow are too broad. I think that ultimately it should be based on `beanClassType` declared in spring's `BeanDefinitionRegistry` (`DataSource` vs `HikariDataSource`), instead of detection of usage spring cloud & hikari in the app as it is now, especially that both spring cloud and embedded databases changes definition of datasource beans. Other option would be to use just one flow with more flexible proxy instead of two existing flows (static proxy + hikari aspect). 

Fix is on the way.
